// Auto-generated by scripts/sync-versions.js - do not edit directly
export const APP_VERSION = "2.1.34";
export const APP_BUILD_DATE = "2026-09-30 8:51 pm";

export function getAppVersion(): string {
    return APP_VERSION;
}

export function getAppBuildDate(): string {
    return APP_BUILD_DATE;
}
