// Auto-generated by scripts/sync-versions.js - do not edit directly
export const APP_VERSION = "2.1.29";
export const APP_BUILD_DATE = "2026-09-21 8:22 pm";

export function getAppVersion(): string {
    try {
        if (typeof chrome !== "undefined" && chrome.runtime?.getManifest) {
            const manifest = chrome.runtime.getManifest();
            if (manifest?.version) {
                return manifest.version;
            }
        }
        if (typeof browser !== "undefined" && browser.runtime?.getManifest) {
            const manifest = browser.runtime.getManifest();
            if (manifest?.version) {
                return manifest.version;
            }
        }
    } catch {
        // Fallback to static version
    }
    return APP_VERSION;
}

export function getAppBuildDate(): string {
    try {
        if (typeof chrome !== "undefined" && chrome.runtime?.getManifest) {
            const manifest = chrome.runtime.getManifest() as any;
            if (manifest?.version_name) {
                const match = manifest.version_name.match(/\((.+)\)/);
                if (match?.[1]) return match[1];
            }
        }
        if (typeof browser !== "undefined" && browser.runtime?.getManifest) {
            const manifest = browser.runtime.getManifest() as any;
            if (manifest?.version_name) {
                const match = manifest.version_name.match(/\((.+)\)/);
                if (match?.[1]) return match[1];
            }
        }
    } catch {
        // Fallback to static date
    }
    return APP_BUILD_DATE;
}
